#!/usr/bin/env python3

import sys

from subprocess import Popen
from argparse import ArgumentParser

COMMANDS = ['xargs', 'primes']

def exec_test(lab_path, command, run_valgrind=False):
    command = [f'./tests/{command}-test.py', f'{lab_path}/{command}']

    if run_valgrind:
        command.append('-v');

    p = Popen(command)
    p.wait()

def exec_all_tests(lab_path, run_valgrind=False):
    for command in COMMANDS:
        exec_test(lab_path, command, run_valgrind)

def make_clean(lab_path):
    p = Popen(['make', 'clean'], cwd=lab_path)
    p.wait()

    return p.returncode

def make(lab_path, command):
    # compile the commands
    if command == 'all':
        p = Popen(['make'], cwd=lab_path)
    else:
        p = Popen(['make', command], cwd=lab_path)
    p.wait()

    return p.returncode

def main(lab_path, command, run_valgrind):
    r = make_clean(lab_path)

    if r > 0:
        print('an error ocurred in make clean')
        sys.exit(-1)

    r = make(lab_path, command)

    if r > 0:
        print('an error ocurred in make')
        sys.exit(-1)

    if command == 'all':
        exec_all_tests(lab_path, run_valgrind)
    else:
        exec_test(lab_path, command, run_valgrind)

    r = make_clean(lab_path)

    if r > 0:
        print('an error ocurred in make clean')
        sys.exit(-1)

if __name__ == '__main__':
    parser = ArgumentParser(description='Test runner for Lab Fork - FISOP')

    parser.add_argument(
        'labpath',
        help='path to the lab under test'
    )

    parser.add_argument(
        '-c',
        '--command',
        choices=COMMANDS,
        default='all',
        help='command to be tested'
    )

    parser.add_argument(
        '-v',
        '--valgrind',
        action='store_true',
        help='Run tests within Valgrind'
    )

    args = parser.parse_args()

    main(args.labpath, args.command, args.valgrind)
